### ISSUE TITLE
The installation isn't detailed enough for non fluent ppl. Failing to install

### ISSUE THREAD

**Issue by drowld** [easlice/bandcamp-downloader#9]
I'm not the biggest noob but even in my case I'm struggling to install and run the script.

I get many errors like 
After  
> pip install -r requirements.txt 

 I had to change it to  

> pip3 install -r requirements.txt  
because I was getting 
`zsh: command not found: pip`

After using
> ./bandcamp-downloader.py --format {mp3-320}
I get 
`ModuleNotFoundError: No module named 'bs4'`

You could specify to format has to be written with a minimal set of infos and that the ] sign are obsolete when using thermal

So I basically can't use the script right now because its unclear what's the entire process like.
But still thanks for the works for the ppl who made it work for them :)

**Comment by easlice** [comment]
Are you doing this on linux or windows?

I'm guessing that there is an issue with how your system has python configured. As in you might have both python2 and python3 installed and don't have pip installed for python2, which may be your system default. Then you ran pip3, installed the packages for python3, but your system is trying to run the script using python2, which doesn't have the right packages.

Also, I don't understand what you mean by:

> and that the ] sign are obsolete when using thermal

Can you clarify that part?

**Comment by JOJ0** [comment]
Hi, interesting project which I will use soon! Thanks already!

Sorry for hijacking but a suggestion on this issue.

A setup.py that does regular python packaging could be used to make sure a xommand wrapper is installed using the correct requirements instead of manual install from requirements file.

This option prevents version mismatch: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires

**Comment by easlice** [comment]
@drowld It's a completely different thing writing a script like this and getting a chrome/firefox extension to work. That was actually the way I first started doing this, but there are a bunch of issues with it because of restrictions to cross-site-scripting and how you gather the list of things to download. Even worse, it wanted to use the browser download dialog, so you had to hit 'OK' for every album or single if you don't auto-placer all downloads into a single folder.

I actually think I might have tried the extension that you linked to, or something that was similar, and ran into issues. For example, it had to paginate your entire collection before it could find the downloads. I never got whatever I was looking at to work right.

The real problem here is that bandcamp doesn't already provide an easy way to do this, or at the least, an API for interfacing with your account and downloads. Either one of those would go a LONG way to making things like this more user friendly.

**Comment by easlice** [comment]
@JOJ0 I appreciate the suggestion. I'm putting this on my list of things to look into.

**Comment by drowld** [comment]
Yeah it really sucks that the bandcamp api doesnt deliver this simple functionality for them.. 
The script in the browser is subpar and tedious but at least it was easy to implement. took me 5 minutes while i spend 3hr not succeeding with this one so. I'm gonna spend 2-3 hour downloading my 500 album collection with bandcamp greasy i have no choice hehe
Thanks anyway

**Comment by easlice** [comment]
@JOJ0 I've been looking at creating a setup.py file, but the issue I'm having is that pip actually detects the poetry toml file and wants to install and do things through poetry instead. So, whether or not you have the setup.py file, if you do:
``` pip install . ```
It wants to download poetry and use that.

I'm not sure what to do here. Personally, I prefer simplicity and conceptually, like being able to use a system default like pip over having to pull in something like poetry for a simple script, but I also know that I am out of touch with the expectations of a python project.

**Comment by easlice** [comment]
@JOJ0 Ok, I got the `setup.py` figured out and, at least on my system, I can install with either pip or poetry. I've also updated the README about it.

Do the changes make sense to you? Is it what you were thinking about? If everything looks good, I'll close this issue.

**Comment by JOJ0** [comment]
That sounds great. I can test install later today/tomorrow if that would help?

**Comment by easlice** [comment]
@JOJ0 Sure, all the updates have been pushed, so everything should be good to take a look at.
